---
- name: Terraform APPLY
  hosts: localhost
  gather_facts: no
  vars:
    dest_dir: "/var/www/miq_tmp/tf-workdir"   
  tasks:
    - name: Ensure workdir exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: "0755"

    - name: Terraform init
      command: terraform -chdir={{ dest_dir }} init -upgrade
      register: tf_init
    - debug: var=tf_init.stdout_lines

    - name: Terraform apply
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "/var/www/miq_tmp/creds/gcp.json"
      command: terraform -chdir={{ dest_dir }} apply -auto-approve
      register: tf_apply
    - debug: var=tf_apply.stdout_lines
